name: Create ZIP file
on: [push]
permissions:
  contents: write
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Zip file
        run: zip -r -q repo/lo-scienziato-pazzo-installer.zip lo-scienziato-pazzo-installer
      
      - name: Commit and push
        run: |
          git config --global user.name 'aandroide'
          git config --global user.email 'aandroide@users.noreply.github.com'
          git commit -am "Automated update zip file"
          git push
          
